# Generated by Django 3.0.3 on 2020-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='foyer',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foyer',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
