# Generated by Django 3.0.3 on 2020-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200513_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='informations_appartement',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
