# Generated by Django 3.0.3 on 2020-05-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_foyer_informations_appartement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prix_total', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='foyer',
            name='telephone',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prix', models.FloatField()),
                ('est_disponible', models.BooleanField()),
                ('commandes', models.ManyToManyField(to='mainsite.Commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='foyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsite.Foyer'),
        ),
    ]
