# Generated by Django 3.0.3 on 2020-05-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200515_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='commandes',
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='mainsite.Produit'),
        ),
    ]
